/**
 * liquiditybank program client.
 *
 * Builds the launch transaction (pump.fun create + liquiditybank register_launch)
 * and exposes helpers to read on-chain launch state.
 *
 * IDL was generated by `anchor build` and copied to liquiditybank.idl.json.
 *
 * Verified against:
 *  - pump.fun mainnet IDL (create discriminator [24,30,200,40,5,28,7,119], 14 accounts)
 *  - PumpSwap mainnet IDL (deposit discriminator [242,35,198,137,...], 15 accounts)
 */

import {
  Connection,
  Keypair,
  PublicKey,
  SystemProgram,
  Transaction,
  TransactionInstruction,
  SYSVAR_RENT_PUBKEY,
} from "@solana/web3.js";
import { Program, AnchorProvider, Idl } from "@coral-xyz/anchor";
import idlJson from "./liquiditybank.idl.json";
import {
  LIQUIDITYBANK_PROGRAM_ID,
  PUMP_PROGRAM_ID,
  PUMP_CREATE_IX_DISCRIMINATOR,
  TOKEN_PROGRAM_ID,
  ASSOCIATED_TOKEN_PROGRAM_ID,
  MPL_TOKEN_METADATA_PROGRAM_ID,
} from "./constants";
import {
  feeOwnerPda,
  launchConfigPda,
  pumpBondingCurvePda,
  pumpEventAuthorityPda,
  pumpGlobalPda,
  pumpMintAuthorityPda,
  metadataPda,
  associatedTokenAddress,
  protocolConfigPda,
  protocolRevenuePda,
} from "./pda";

export const PROGRAM_ID = LIQUIDITYBANK_PROGRAM_ID;

// ---------------------------------------------------------------------------
// Anchor program client (for reads + liquiditybank method calls)
// ---------------------------------------------------------------------------
export function getProgram(provider: AnchorProvider) {
  return new Program(idlJson as unknown as Idl, provider);
}

// ---------------------------------------------------------------------------
// Borsh-style string encoding for the pump.fun `create` ix
// ---------------------------------------------------------------------------
function encodeString(s: string): Buffer {
  const bytes = Buffer.from(s, "utf8");
  const len = Buffer.alloc(4);
  len.writeUInt32LE(bytes.length, 0);
  return Buffer.concat([len, bytes]);
}

// ---------------------------------------------------------------------------
// Build the pump.fun `create` instruction.
// Verified against pump.fun mainnet IDL.
// Args: name (string), symbol (string), uri (string), creator (pubkey)
// 14 accounts in IDL order.
// ---------------------------------------------------------------------------
export type CreateArgs = {
  name: string;
  symbol: string;
  uri: string; // metadata URI (json with name/symbol/image/description)
  user: PublicKey; // signer / payer
  mint: PublicKey; // new mint signer (Keypair generated by caller)
  creator: PublicKey; // creator on the bonding curve — set to fee_owner PDA
};

export function buildPumpCreateIx(args: CreateArgs): TransactionInstruction {
  const [bondingCurve] = pumpBondingCurvePda(args.mint);
  const [mintAuthority] = pumpMintAuthorityPda();
  const [global] = pumpGlobalPda();
  const [eventAuthority] = pumpEventAuthorityPda();
  const [metadata] = metadataPda(args.mint);

  const associatedBondingCurve = associatedTokenAddress(
    bondingCurve,
    args.mint
  );

  const data = Buffer.concat([
    PUMP_CREATE_IX_DISCRIMINATOR,
    encodeString(args.name),
    encodeString(args.symbol),
    encodeString(args.uri),
    args.creator.toBuffer(),
  ]);

  const keys = [
    { pubkey: args.mint, isSigner: true, isWritable: true },
    { pubkey: mintAuthority, isSigner: false, isWritable: false },
    { pubkey: bondingCurve, isSigner: false, isWritable: true },
    { pubkey: associatedBondingCurve, isSigner: false, isWritable: true },
    { pubkey: global, isSigner: false, isWritable: false },
    { pubkey: MPL_TOKEN_METADATA_PROGRAM_ID, isSigner: false, isWritable: false },
    { pubkey: metadata, isSigner: false, isWritable: true },
    { pubkey: args.user, isSigner: true, isWritable: true },
    { pubkey: SystemProgram.programId, isSigner: false, isWritable: false },
    { pubkey: TOKEN_PROGRAM_ID, isSigner: false, isWritable: false },
    { pubkey: ASSOCIATED_TOKEN_PROGRAM_ID, isSigner: false, isWritable: false },
    { pubkey: SYSVAR_RENT_PUBKEY, isSigner: false, isWritable: false },
    { pubkey: eventAuthority, isSigner: false, isWritable: false },
    { pubkey: PUMP_PROGRAM_ID, isSigner: false, isWritable: false },
  ];

  return new TransactionInstruction({
    programId: PUMP_PROGRAM_ID,
    keys,
    data,
  });
}

// ---------------------------------------------------------------------------
// Build the liquiditybank `register_launch` instruction via Anchor's IDL.
// ---------------------------------------------------------------------------
export async function buildRegisterLaunchIx(
  provider: AnchorProvider,
  args: { registrant: PublicKey; mint: PublicKey }
): Promise<TransactionInstruction> {
  const program = getProgram(provider);
  const [feeOwner] = feeOwnerPda(args.mint);
  const [launchConfig] = launchConfigPda(args.mint);
  const [protocolConfig] = protocolConfigPda();
  const [protocolRevenue] = protocolRevenuePda();

  return await program.methods
    .registerLaunch()
    .accounts({
      registrant: args.registrant,
      mint: args.mint,
      feeOwner,
      launchConfig,
      protocolConfig,
      protocolRevenue,
      systemProgram: SystemProgram.programId,
    })
    .instruction();
}

// ---------------------------------------------------------------------------
// Top-level: assemble the full launch transaction.
//
// Returns a transaction containing:
//   1. pump.fun `create` (with fee_owner_pda as creator role)
//   2. liquiditybank `register_launch` (pays 0.02 SOL protocol fee, initializes LaunchConfig)
//
// The caller must sign with BOTH the user wallet AND the new mint keypair.
// ---------------------------------------------------------------------------
export type LaunchPlan = {
  name: string;
  ticker: string;
  description: string;
  imageUrl: string;
  metadataUri?: string; // pre-uploaded JSON metadata URI; if absent we derive
  initialBuy: number;
};

export async function buildLaunchTransaction(
  connection: Connection,
  provider: AnchorProvider,
  plan: LaunchPlan,
  payer: PublicKey
): Promise<{ tx: Transaction; mintKeypair: Keypair }> {
  const mintKeypair = Keypair.generate();
  const [feeOwner] = feeOwnerPda(mintKeypair.publicKey);

  // For a real launch the metadata JSON should be uploaded to IPFS/Arweave
  // first; for the v0 we fall back to a data: URI built from the form.
  const metadataUri =
    plan.metadataUri ||
    "data:application/json;base64," +
      Buffer.from(
        JSON.stringify({
          name: plan.name,
          symbol: plan.ticker,
          description: plan.description,
          image: plan.imageUrl || undefined,
        })
      ).toString("base64");

  const createIx = buildPumpCreateIx({
    name: plan.name,
    symbol: plan.ticker,
    uri: metadataUri,
    user: payer,
    mint: mintKeypair.publicKey,
    creator: feeOwner,
  });

  const registerIx = await buildRegisterLaunchIx(provider, {
    registrant: payer,
    mint: mintKeypair.publicKey,
  });

  const tx = new Transaction();
  tx.add(createIx, registerIx);
  const { blockhash, lastValidBlockHeight } =
    await connection.getLatestBlockhash();
  tx.recentBlockhash = blockhash;
  tx.lastValidBlockHeight = lastValidBlockHeight;
  tx.feePayer = payer;

  // Partial-sign with the mint keypair so the wallet only needs to add
  // the user signature.
  tx.partialSign(mintKeypair);

  return { tx, mintKeypair };
}

// ---------------------------------------------------------------------------
// Read all LaunchConfig accounts (powers the ledger page).
// ---------------------------------------------------------------------------
export async function listLaunches(provider: AnchorProvider) {
  const program = getProgram(provider);
  // @ts-expect-error - account namespace is generated from IDL at runtime
  const accounts = await program.account.launchConfig.all();
  return accounts.map((a: any) => ({
    publicKey: a.publicKey.toBase58(),
    mint: a.account.mint.toBase58(),
    registrant: a.account.registrant.toBase58(),
    createdAt: Number(a.account.createdAt),
    cumulativeFeesCollected: BigInt(a.account.cumulativeFeesCollected.toString()),
    cumulativeLpSolAdded: BigInt(a.account.cumulativeLpSolAdded.toString()),
    cumulativeLpBurned: BigInt(a.account.cumulativeLpBurned.toString()),
    crankCount: Number(a.account.crankCount),
  }));
}

// ---------------------------------------------------------------------------
// Formatting helpers
// ---------------------------------------------------------------------------
export function formatSol(lamports: bigint): string {
  const n = Number(lamports) / 1_000_000_000;
  if (n >= 1000) return `${(n / 1000).toFixed(1)}k SOL`;
  if (n >= 1) return `${n.toFixed(2)} SOL`;
  return `${n.toFixed(4)} SOL`;
}

export function formatRelative(ts: number): string {
  const diff = Math.floor(Date.now() / 1000) - ts;
  if (diff < 60) return `${diff}s ago`;
  if (diff < 3600) return `${Math.floor(diff / 60)}m ago`;
  if (diff < 86400) return `${Math.floor(diff / 3600)}h ago`;
  return `${Math.floor(diff / 86400)}d ago`;
}

export function shorten(s: string, n = 6): string {
  return `${s.slice(0, n)}…${s.slice(-n)}`;
}

// ---------------------------------------------------------------------------
// Placeholder data for the dashboard while the chain is empty.
// Replaced by listLaunches() once there are real on-chain entries.
// ---------------------------------------------------------------------------
export const PLACEHOLDER_LAUNCHES = [
  {
    publicKey: "",
    mint: "8z3kQpL9aJ4tQwR7nXp2vF6mYz1bC5dE8fG9hI0jK1mN",
    registrant: "",
    name: "Brutalist",
    ticker: "BRUT",
    createdAt: Math.floor(Date.now() / 1000) - 60 * 60 * 27,
    cumulativeFeesCollected: 4_820_000_000n,
    cumulativeLpSolAdded: 4_320_000_000n,
    cumulativeLpBurned: 18_400_000_000n,
    crankCount: 9,
  },
  {
    publicKey: "",
    mint: "3qVbT9MnX2pK1jL8wY7sR5dE2nF6tG4hC9bA0mZ3xJ8u",
    registrant: "",
    name: "Pyrite",
    ticker: "PYR",
    createdAt: Math.floor(Date.now() / 1000) - 60 * 60 * 4,
    cumulativeFeesCollected: 1_280_000_000n,
    cumulativeLpSolAdded: 1_080_000_000n,
    cumulativeLpBurned: 5_240_000_000n,
    crankCount: 2,
  },
  {
    publicKey: "",
    mint: "7Lh2Nw9xPq4mS8jR3fB6yK1cD0vU5tE2gI9aO7zQ4nXs",
    registrant: "",
    name: "Ashfall",
    ticker: "ASH",
    createdAt: Math.floor(Date.now() / 1000) - 60 * 60 * 96,
    cumulativeFeesCollected: 22_400_000_000n,
    cumulativeLpSolAdded: 21_900_000_000n,
    cumulativeLpBurned: 98_300_000_000n,
    crankCount: 41,
  },
];
